spring:
  profiles:
    group:
      deploy: s3Bucket

  application:
    name: Spring_boots
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spring-boots-db.c62sszsbm7i4.ap-northeast-2.rds.amazonaws.com:3306/spring-boots-db
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    #defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://xsadxbhpffmfhfsx.tunnel-pt.elice.io/login/oauth2/code/google"


jwt:
  issuer: test@example.com
  secret_key: spring-boots
  secret: ${JWT_SECRET_KEY}
  token:
    refresh-expires: 604800000
    access-expires: 900000

admin:
  code: ${ADMIN_CODE} #관리자코드
